### ISSUE TITLE
Issue Calling `window.Intercom` on beta signup form submission

### ISSUE THREAD

**Issue by siromivel** [OpenZeppelin/openzeppelin-token-registry#13]
Hey ZeppelinOS, I'm running into an issue submitting the beta signup form:
![image](https://user-images.githubusercontent.com/7109332/53688698-236d3080-3d05-11e9-9b50-8b88d6005d7d.png)

If noone else gets to it I'll take a look pulling the repo and opening a PR in the next few days here.

**Comment by siromivel** [comment]
It looks like this is broken due a null value for `REACT_APP_INTERCOM_APP_ID`; by simply removing that check in `index.js` the form submission will work again as the missing ID is preventing Intercom from being injected.

That's probably undesirable as it will lead to emailing `undefined@intercom-mail` or similar unexpected behavior. I'm guessing a better fix would be to pass whatever the correct value is for that in the production environment.

**Comment by rrecuero** [comment]
Thank you. We just triggered a new deploy with the correct variable set :)

**Comment by siromivel** [comment]
@rrecuero Wanted to let you know that I just tried again and am encountering the same issue still.
