### ISSUE TITLE
Replace "endorse" with "vouch"

### ISSUE THREAD

**Issue by come-maiz** [OpenZeppelin/openzeppelin-token-registry#7]
The word "endorse" is [in the UI](https://github.com/zeppelinos/zos-registry/blob/61675c8d63b5b2ed3e87e6cf64fe8cf09df76bda/src/components/packages/PackageDetails.jsx#L122) and in the CSS code.

This is a synonym for "vouch", which is the word we are using for this concept in ZeppelinOS. Synonyms for the core concepts make them harder to understand, so we should avoid them. 

Please replace everything that says endorse with vouch.

**Comment by asselstine** [comment]
Done https://github.com/DeltaCamp/zos-registry/pull/33
